version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn resistance.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000 # port 8000 is exposed internally to other ports
    env_file:
      - ./resistance/.env.prod
      
  daphne:
    extends:
      service: web
    command: daphne -b 0.0.0.0 --port 8001 resistance.asgi:application #--proxy-headers
    ports:
      - 8001:8001
    expose:
      - 8001
    depends_on:
      - web
      - redis
    links:
      - redis

  static:
    extends:
      service: web
    command: python manage.py collectstatic --no-input --clear
    depends_on:
      - web
  
  redis:
    image: redis:5.0.5-alpine
    hostname: redis-container
    expose:
      - 6379
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web
      - daphne

volumes:
    static_volume: