# Docker engine release 19.03.0+
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./resistance/.env.dev
      
  redis:
    image: redis:5.0.5-alpine
    hostname: redis-container
    expose:
      - 6379
    ports:
      - 6379:6379