# Docker engine release 19.03.0+
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./resistance/.env.dev
      
  redis:
    image: redis:5.0.5-alpine
    hostname: redis-container
    expose:
      - 6379
    ports:
      - 6379:6379

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresqpl/data/
    
  db_migrate:
    extends:
      service: web
    command: python manage.py migrate --noinput

volumes:
    postgres_data: