version: '3.8'

services:
  daphne:
    build: .
    working_dir: /home/app/web
    command: daphne -b 0.0.0.0 -p 8080 resistance.asgi:channel_layer
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn resistance.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000 # port 8000 is exposed internally to other ports
    env_file:
      - ./resistance/.env.prod
  
  static:
    extends:
      service: web
    command: python manage.py collectstatic --no-input --clear
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web
      - daphne

volumes:
    static_volume: