# Generated by Django 3.1.13 on 2021-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_onlinegames_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onlinegames',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
