# Generated by Django 3.2.4 on 2021-07-21 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('roles', models.CharField(max_length=5000)),
                ('settings', models.CharField(max_length=1000)),
                ('num_players', models.CharField(max_length=2)),
                ('winning_team', models.CharField(max_length=50)),
                ('in_session', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
